[package]
name = "auth"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
chacha20poly1305.workspace = true
contracts = { path = "../contracts" }
http.workspace = true
jsonwebtoken.workspace = true
jwt-authorizer.workspace = true
metrics.workspace = true
openidconnect.workspace = true
rand.workspace = true
reqwest.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
sqlx.workspace = true
subtle.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[dependencies.async-nats]
workspace = true

[dev-dependencies]
axum.workspace = true
environment-service = { path = "../../services/environment-service" }
rcgen.workspace = true
scraper.workspace = true
tempfile.workspace = true
tokio.workspace = true

[lints]
workspace = true
