apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: labweaver-demo-web
  labels:
    {{- include "labweaverDemo.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: labweaver-demo
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress, Egress]
  ingress: []
  egress: []
