apiVersion: v1
kind: Service
metadata:
  name: labweaver-demo-web
  labels:
    {{- include "labweaverDemo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: labweaver-demo
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http, protocol: TCP}
