[package]
name = "artifact-store"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
aws-config.workspace = true
aws-credential-types.workspace = true
aws-sdk-s3.workspace = true
aws-smithy-runtime = { version = "=1.7.8", features = ["tls-rustls"] }
base64.workspace = true
contracts = { path = "../contracts" }
hyper-rustls = "=0.24.2"
rustls = "=0.21.12"
rustls-native-certs.workspace = true
rustls-pemfile.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
reqwest.workspace = true
testcontainers = { version = "=0.25.0", features = ["blocking"] }
tokio.workspace = true

[lints]
workspace = true
