[package]
name = "access-service"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-nats = { version = "=0.45.0", default-features = false, features = ["ring", "server_2_10", "server_2_11"] }
axum.workspace = true
auth = { path = "../../crates/auth" }
contracts = { path = "../../crates/contracts" }
futures-util = "0.3.31"
hyper-util.workspace = true
hyper.workspace = true
jsonwebtoken.workspace = true
jwt-authorizer.workspace = true
metrics.workspace = true
persistence-sqlx = { path = "../../crates/persistence-sqlx" }
rand.workspace = true
serde.workspace = true
serde_jcs.workspace = true
serde_json.workspace = true
sha2.workspace = true
reqwest.workspace = true
rustls.workspace = true
sqlx.workspace = true
telemetry = { path = "../../crates/telemetry" }
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

[lints]
workspace = true

[dev-dependencies]
testcontainers = { version = "0.25.0", features = ["blocking", "properties-config"] }
testcontainers-modules = { version = "0.13.0", features = ["postgres"] }
