//! Server-owned materialization of Claude container build-context plans.
//!
//! This module deliberately has no Claude process or prompt logic. It accepts a small, typed
//! plan, validates it against the already-authorized package scope, and either returns an
//! explicitly selected submitted context or writes a new immutable context object.

use std::collections::BTreeSet;
use std::sync::Arc;

use artifact_store::{ImmutableObjectStore, S3ImmutableObjectStore};
use async_trait::async_trait;
use contracts::{ArtifactRef, CourseId, ProblemPackageId, ProjectId, Revision, UtcTimestamp};
use flate2::{Compression, write::GzEncoder};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use thiserror::Error;
use time::OffsetDateTime;

use contracts::authoring::ProblemPackage;

use crate::generated_artifacts::{
    GeneratedArtifactKind, GeneratedArtifactStore, GeneratedArtifactStoreError,
};

const BUILD_CONTEXT_MEDIA_TYPES: [&str; 2] = [
    "application/vnd.oci.image.layer.v1.tar+gzip",
    "application/gzip",
];
const GENERATED_CONTEXT_PREFIX: &str = "generated-build-contexts";
const MAX_RECIPE_FILES: usize = 64;
const MAX_RECIPE_FILE_BYTES: usize = 512 * 1024;
const MAX_RECIPE_BYTES: usize = 8 * 1024 * 1024;
const BUILD_CONTEXT_MEDIA_TYPE: &str = "application/vnd.oci.image.layer.v1.tar+gzip";
const WORK_SCRIPT_MEDIA_TYPE: &str = "text/x-shellscript";
const GENERATED_WORK_SCRIPT_PREFIX: &str = "generated-work-configuration-scripts";
const MAX_WORK_SCRIPT_BYTES: usize = 512 * 1024;

/// The provider-facing container build plan. Artifact identities are intentionally absent.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "mode", rename_all = "snake_case", deny_unknown_fields)]
pub enum ContainerBuildRecipe {
    /// Files generated by the authorized LLM invocation and materialized by the Agent service.
    Generated { files: Vec<RecipeFile> },
    /// A package context selected by an explicit relative package path.
    Submitted { source_path: String },
}

/// One bounded UTF-8 file in a generated build context.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case", deny_unknown_fields)]
pub struct RecipeFile {
    pub path: String,
    pub content: String,
}

/// Object-store and plan validation failure during candidate materialization.
#[derive(Clone, Debug, Eq, Error, PartialEq)]
pub enum CandidateMaterializationError {
    /// The plan is malformed or outside the package/project scope.
    #[error("candidate build recipe is invalid")]
    InvalidPlan,
    /// The configured object store could not persist or verify the generated context.
    #[error("candidate build context could not be persisted")]
    Storage,
    /// The materializer was configured without the package required by the invocation.
    #[error("candidate build recipe package scope is unavailable")]
    ScopeUnavailable,
}

impl CandidateMaterializationError {
    /// Returns a stable diagnostic for the materialization boundary.
    #[must_use]
    pub const fn diagnostic_code(&self) -> &'static str {
        match self {
            Self::InvalidPlan => "LW_AGENT_CANDIDATE_MATERIALIZATION_INVALID_PLAN",
            Self::Storage => "LW_AGENT_CANDIDATE_MATERIALIZATION_STORAGE_FAILED",
            Self::ScopeUnavailable => "LW_AGENT_CANDIDATE_MATERIALIZATION_SCOPE_UNAVAILABLE",
        }
    }
}

impl From<GeneratedArtifactStoreError> for CandidateMaterializationError {
    fn from(_: GeneratedArtifactStoreError) -> Self {
        Self::Storage
    }
}

/// Server-owned boundary used by the Claude adapter to bind a generated context.
#[async_trait]
pub trait EnvironmentCandidateMaterializer: Send + Sync {
    /// Materializes an explicit provider plan under one exact immutable package scope.
    async fn materialize(
        &self,
        project_id: ProjectId,
        course_id: Option<CourseId>,
        package_id: ProblemPackageId,
        package_revision: Revision,
        plan: &Value,
    ) -> Result<ArtifactRef, CandidateMaterializationError>;
}

/// Server-owned boundary for persisting scripts generated by the Work configuration run.
///
/// A Work draft contains script content, never a package path or object identity.  The Agent
/// service is the only component allowed to turn that content into immutable artifacts; Control
/// later copies those exact references into a preauthorization.
#[async_trait]
pub trait WorkConfigurationArtifactMaterializer: Send + Sync {
    /// Persists the generated configuration and optional verification script under one package
    /// scope and returns their immutable references.
    async fn materialize_scripts(
        &self,
        project_id: ProjectId,
        course_id: Option<CourseId>,
        package_id: ProblemPackageId,
        package_revision: Revision,
        script: &str,
        verification_script: Option<&str>,
    ) -> Result<(ArtifactRef, Option<ArtifactRef>), CandidateMaterializationError>;
}

/// Production materializer backed by the configured immutable object store.
#[derive(Clone)]
pub struct S3EnvironmentCandidateMaterializer {
    objects: Arc<S3ImmutableObjectStore>,
    package: ProblemPackage,
    generated_artifacts: GeneratedArtifactStore,
}

impl std::fmt::Debug for S3EnvironmentCandidateMaterializer {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("S3EnvironmentCandidateMaterializer")
            .field("store_binding", &self.objects.binding())
            .field("package_id", &self.package.id)
            .field("project_id", &self.package.project_id)
            .field("course_id", &self.package.course_id)
            .finish_non_exhaustive()
    }
}

impl S3EnvironmentCandidateMaterializer {
    /// Creates a materializer bound to the exact package already admitted by Control.
    #[must_use]
    pub fn new(
        objects: Arc<S3ImmutableObjectStore>,
        package: ProblemPackage,
        generated_artifacts: GeneratedArtifactStore,
    ) -> Self {
        Self {
            objects,
            package,
            generated_artifacts,
        }
    }

    fn validate_scope(
        &self,
        project_id: ProjectId,
        course_id: Option<CourseId>,
        package_id: ProblemPackageId,
        package_revision: Revision,
    ) -> Result<(), CandidateMaterializationError> {
        if self.package.project_id != project_id
            || self.package.course_id != course_id
            || self.package.id != package_id
            || self.package.revision != package_revision
        {
            return Err(CandidateMaterializationError::ScopeUnavailable);
        }
        Ok(())
    }

    fn submitted_context(
        &self,
        source_path: &str,
    ) -> Result<ArtifactRef, CandidateMaterializationError> {
        contracts::validate_relative_path(source_path)
            .map_err(|_| CandidateMaterializationError::InvalidPlan)?;
        let file = self
            .package
            .files
            .iter()
            .find(|file| file.path == source_path)
            .ok_or(CandidateMaterializationError::InvalidPlan)?;
        if !BUILD_CONTEXT_MEDIA_TYPES.contains(&file.object.media_type.as_str()) {
            return Err(CandidateMaterializationError::InvalidPlan);
        }
        Ok(file.object.clone())
    }

    async fn generated_context(
        &self,
        files: &[RecipeFile],
    ) -> Result<ArtifactRef, CandidateMaterializationError> {
        let archive = pack_recipe(files)?;
        let artifact_id = contracts::ArtifactId::new();
        let key = self
            .objects
            .scoped_key(&format!(
                "{GENERATED_CONTEXT_PREFIX}/{}/{}.tar.gz",
                self.package.project_id, artifact_id
            ))
            .map_err(|error| {
                tracing::warn!(
                    event = "agent.candidate_materialization.failed",
                    component = "candidate-materializer",
                    operation = "artifact.key",
                    outcome = "failed",
                    artifact_kind = "build_context",
                    failure_stage = "object_key",
                    diagnostic_code = error.diagnostic_code(),
                    error_kind = ?error,
                    retryable = false,
                );
                CandidateMaterializationError::Storage
            })?;
        let now = current_timestamp().map_err(|()| CandidateMaterializationError::Storage)?;
        let object = self
            .objects
            .put_governance_locked(
                &key,
                &archive,
                BUILD_CONTEXT_MEDIA_TYPE,
                now,
                self.package.retention.retain_until,
            )
            .await
            .map_err(|error| {
                tracing::warn!(
                    event = "agent.candidate_materialization.failed",
                    component = "candidate-materializer",
                    operation = "artifact.write",
                    outcome = "failed",
                    artifact_kind = "build_context",
                    failure_stage = "object_upload",
                    diagnostic_code = error.diagnostic_code(),
                    error_kind = ?error,
                    retryable = false,
                );
                CandidateMaterializationError::Storage
            })?;
        self.generated_artifacts
            .register(
                self.package.project_id,
                self.package.course_id,
                self.package.id,
                self.package.revision,
                GeneratedArtifactKind::BuildContext,
                &key,
                object.reference.clone(),
                &archive,
            )
            .await
            .map_err(|error| {
                tracing::warn!(
                    event = "agent.candidate_materialization.failed",
                    component = "candidate-materializer",
                    operation = "artifact.metadata_register",
                    outcome = "failed",
                    artifact_kind = "build_context",
                    failure_stage = "metadata_register",
                    diagnostic_code = generated_artifact_diagnostic(&error),
                    error_kind = ?error,
                    retryable = false,
                );
                CandidateMaterializationError::from(error)
            })?;
        Ok(object.reference)
    }
}

#[async_trait]
impl EnvironmentCandidateMaterializer for S3EnvironmentCandidateMaterializer {
    async fn materialize(
        &self,
        project_id: ProjectId,
        course_id: Option<CourseId>,
        package_id: ProblemPackageId,
        package_revision: Revision,
        plan: &Value,
    ) -> Result<ArtifactRef, CandidateMaterializationError> {
        self.validate_scope(project_id, course_id, package_id, package_revision)?;
        let recipe: ContainerBuildRecipe = serde_json::from_value(plan.clone())
            .map_err(|_| CandidateMaterializationError::InvalidPlan)?;
        match recipe {
            ContainerBuildRecipe::Generated { files } => self.generated_context(&files).await,
            ContainerBuildRecipe::Submitted { source_path } => self.submitted_context(&source_path),
        }
    }
}

#[async_trait]
impl WorkConfigurationArtifactMaterializer for S3EnvironmentCandidateMaterializer {
    async fn materialize_scripts(
        &self,
        project_id: ProjectId,
        course_id: Option<CourseId>,
        package_id: ProblemPackageId,
        package_revision: Revision,
        script: &str,
        verification_script: Option<&str>,
    ) -> Result<(ArtifactRef, Option<ArtifactRef>), CandidateMaterializationError> {
        self.validate_scope(project_id, course_id, package_id, package_revision)?;
        let script_artifact = self
            .generated_script(script, GeneratedArtifactKind::WorkScript)
            .await?;
        let verification_artifact = match verification_script {
            Some(content) => Some(
                self.generated_script(content, GeneratedArtifactKind::VerificationScript)
                    .await?,
            ),
            None => None,
        };
        Ok((script_artifact, verification_artifact))
    }
}

impl S3EnvironmentCandidateMaterializer {
    async fn generated_script(
        &self,
        content: &str,
        kind: GeneratedArtifactKind,
    ) -> Result<ArtifactRef, CandidateMaterializationError> {
        if content.is_empty() || content.len() > MAX_WORK_SCRIPT_BYTES {
            return Err(CandidateMaterializationError::InvalidPlan);
        }
        let bytes = content.as_bytes();
        let artifact_id = contracts::ArtifactId::new();
        let key = self
            .objects
            .scoped_key(&format!(
                "{GENERATED_WORK_SCRIPT_PREFIX}/{}/{}.sh",
                self.package.project_id, artifact_id
            ))
            .map_err(|error| {
                tracing::warn!(
                    event = "agent.candidate_materialization.failed",
                    component = "candidate-materializer",
                    operation = "artifact.key",
                    outcome = "failed",
                    artifact_kind = ?kind,
                    failure_stage = "object_key",
                    diagnostic_code = error.diagnostic_code(),
                    error_kind = ?error,
                    retryable = false,
                );
                CandidateMaterializationError::Storage
            })?;
        let now = current_timestamp().map_err(|()| CandidateMaterializationError::Storage)?;
        let object = self
            .objects
            .put_governance_locked(
                &key,
                bytes,
                WORK_SCRIPT_MEDIA_TYPE,
                now,
                self.package.retention.retain_until,
            )
            .await
            .map_err(|error| {
                tracing::warn!(
                    event = "agent.candidate_materialization.failed",
                    component = "candidate-materializer",
                    operation = "artifact.write",
                    outcome = "failed",
                    artifact_kind = ?kind,
                    failure_stage = "object_upload",
                    diagnostic_code = error.diagnostic_code(),
                    error_kind = ?error,
                    retryable = false,
                );
                CandidateMaterializationError::Storage
            })?;
        self.generated_artifacts
            .register(
                self.package.project_id,
                self.package.course_id,
                self.package.id,
                self.package.revision,
                kind,
                &key,
                object.reference.clone(),
                bytes,
            )
            .await
            .map_err(|error| {
                tracing::warn!(
                    event = "agent.candidate_materialization.failed",
                    component = "candidate-materializer",
                    operation = "artifact.metadata_register",
                    outcome = "failed",
                    artifact_kind = ?kind,
                    failure_stage = "metadata_register",
                    diagnostic_code = generated_artifact_diagnostic(&error),
                    error_kind = ?error,
                    retryable = false,
                );
                CandidateMaterializationError::from(error)
            })?;
        Ok(object.reference)
    }
}

/// Returns the provider-facing JSON schema for a container build recipe.
#[must_use]
pub fn recipe_schema() -> Value {
    serde_json::json!({
        "type": "object",
        "oneOf": [
            {
                "type": "object",
                "required": ["mode", "files"],
                "properties": {
                    "mode": {"const": "generated"},
                    "files": {
                        "type": "array",
                        "minItems": 1,
                        "maxItems": MAX_RECIPE_FILES,
                        "items": {
                            "type": "object",
                            "required": ["path", "content"],
                            "additionalProperties": false,
                            "properties": {
                                "path": {"type": "string", "minLength": 1, "maxLength": 1024},
                                "content": {"type": "string", "minLength": 1, "maxLength": MAX_RECIPE_FILE_BYTES}
                            }
                        }
                    }
                },
                "additionalProperties": false
            },
            {
                "type": "object",
                "required": ["mode", "source_path"],
                "properties": {
                    "mode": {"const": "submitted"},
                    "source_path": {"type": "string", "minLength": 1, "maxLength": 1024}
                },
                "additionalProperties": false
            }
        ]
    })
}

fn pack_recipe(files: &[RecipeFile]) -> Result<Vec<u8>, CandidateMaterializationError> {
    if files.is_empty() || files.len() > MAX_RECIPE_FILES {
        return Err(CandidateMaterializationError::InvalidPlan);
    }
    let mut paths = BTreeSet::new();
    let mut total_bytes = 0_usize;
    let mut validated = Vec::with_capacity(files.len());
    for file in files {
        contracts::validate_relative_path(&file.path)
            .map_err(|_| CandidateMaterializationError::InvalidPlan)?;
        if file.content.is_empty()
            || file.content.len() > MAX_RECIPE_FILE_BYTES
            || !paths.insert(file.path.clone())
        {
            return Err(CandidateMaterializationError::InvalidPlan);
        }
        total_bytes = total_bytes
            .checked_add(file.content.len())
            .ok_or(CandidateMaterializationError::InvalidPlan)?;
        if total_bytes > MAX_RECIPE_BYTES {
            return Err(CandidateMaterializationError::InvalidPlan);
        }
        validated.push(file);
    }
    if !paths.contains("Dockerfile") {
        return Err(CandidateMaterializationError::InvalidPlan);
    }

    let mut archive = Vec::new();
    {
        let encoder = GzEncoder::new(&mut archive, Compression::default());
        let mut builder = tar::Builder::new(encoder);
        builder.follow_symlinks(false);
        for file in validated {
            let bytes = file.content.as_bytes();
            let mut header = tar::Header::new_gnu();
            header.set_size(
                u64::try_from(bytes.len())
                    .map_err(|_| CandidateMaterializationError::InvalidPlan)?,
            );
            header.set_mode(0o644);
            header.set_mtime(0);
            header.set_uid(0);
            header.set_gid(0);
            header.set_cksum();
            builder
                .append_data(&mut header, &file.path, bytes)
                .map_err(|_| CandidateMaterializationError::Storage)?;
        }
        let encoder = builder
            .into_inner()
            .map_err(|_| CandidateMaterializationError::Storage)?;
        encoder
            .finish()
            .map_err(|_| CandidateMaterializationError::Storage)?;
    }
    if archive.is_empty() || archive.len() > MAX_RECIPE_BYTES {
        return Err(CandidateMaterializationError::InvalidPlan);
    }
    Ok(archive)
}

fn generated_artifact_diagnostic(error: &GeneratedArtifactStoreError) -> &'static str {
    match error {
        GeneratedArtifactStoreError::InvalidMetadata => {
            "LW_AGENT_GENERATED_ARTIFACT_METADATA_INVALID"
        }
        GeneratedArtifactStoreError::NotFound => "LW_AGENT_GENERATED_ARTIFACT_NOT_FOUND",
        GeneratedArtifactStoreError::IdentityMismatch => {
            "LW_AGENT_GENERATED_ARTIFACT_IDENTITY_MISMATCH"
        }
        GeneratedArtifactStoreError::Persistence => {
            "LW_AGENT_GENERATED_ARTIFACT_METADATA_PERSISTENCE_FAILED"
        }
        GeneratedArtifactStoreError::Storage(error) => error.diagnostic_code(),
    }
}

fn current_timestamp() -> Result<UtcTimestamp, ()> {
    let now = OffsetDateTime::now_utc();
    let now = now
        .replace_nanosecond((now.nanosecond() / 1_000_000) * 1_000_000)
        .map_err(|_| ())?;
    UtcTimestamp::from_utc(now).map_err(|_| ())
}

#[cfg(test)]
mod tests {
    use super::{CandidateMaterializationError, ContainerBuildRecipe, RecipeFile, pack_recipe};
    use serde_json::json;

    #[test]
    fn generated_recipe_is_deterministic_and_requires_dockerfile() {
        let files = vec![
            RecipeFile {
                path: "Dockerfile".to_owned(),
                content: "FROM scratch\n".to_owned(),
            },
            RecipeFile {
                path: "app.txt".to_owned(),
                content: "generated\n".to_owned(),
            },
        ];
        assert_eq!(pack_recipe(&files), pack_recipe(&files));
        let missing = vec![RecipeFile {
            path: "app.txt".to_owned(),
            content: "generated\n".to_owned(),
        }];
        assert_eq!(
            pack_recipe(&missing),
            Err(CandidateMaterializationError::InvalidPlan)
        );
    }

    #[test]
    fn recipe_rejects_duplicate_or_unsafe_files() {
        for files in [
            vec![
                RecipeFile {
                    path: "Dockerfile".to_owned(),
                    content: "FROM scratch\n".to_owned(),
                },
                RecipeFile {
                    path: "Dockerfile".to_owned(),
                    content: "FROM busybox\n".to_owned(),
                },
            ],
            vec![RecipeFile {
                path: "../Dockerfile".to_owned(),
                content: "FROM scratch\n".to_owned(),
            }],
        ] {
            assert_eq!(
                pack_recipe(&files),
                Err(CandidateMaterializationError::InvalidPlan)
            );
        }
    }

    #[test]
    fn plan_has_no_artifact_identity_fields() {
        let result = serde_json::from_value::<ContainerBuildRecipe>(json!({
            "mode": "submitted",
            "source_path": "context.tar.gz",
            "artifactId": "not-accepted"
        }));
        assert!(result.is_err());
    }
}
