//! Agent-owned metadata for immutable objects generated by an Agent run.
//!
//! `ArtifactRef` intentionally contains no backend object key or content digest.  That keeps
//! public contracts independent from the object-store layout, but it also means the owning
//! service must retain the resolution.  This module is that small Agent-owned authority.  It is
//! used for generated build contexts and Work scripts; submitted package files continue to be
//! resolved by Control from its package tables.

use std::str::FromStr;

use artifact_store::{ImmutableObjectStore, ObjectStoreError, S3ImmutableObjectStore};
pub use contracts::http::{GeneratedArtifactKind, GeneratedArtifactQuery, GeneratedArtifactRecord};
use contracts::{ArtifactId, ArtifactRef, CourseId, ProblemPackageId, ProjectId, Revision};
use persistence_sqlx::Sha256Digest;
use sqlx::{PgPool, Row};
use thiserror::Error;

const MAX_OBJECT_KEY_BYTES: usize = 2 * 1024;

fn kind_name(kind: GeneratedArtifactKind) -> &'static str {
    match kind {
        GeneratedArtifactKind::BuildContext => "build_context",
        GeneratedArtifactKind::WorkScript => "work_script",
        GeneratedArtifactKind::VerificationScript => "verification_script",
    }
}

fn parse_kind(value: &str) -> Result<GeneratedArtifactKind, GeneratedArtifactStoreError> {
    match value {
        "build_context" => Ok(GeneratedArtifactKind::BuildContext),
        "work_script" => Ok(GeneratedArtifactKind::WorkScript),
        "verification_script" => Ok(GeneratedArtifactKind::VerificationScript),
        _ => Err(GeneratedArtifactStoreError::InvalidMetadata),
    }
}

fn validate_record(record: &GeneratedArtifactRecord) -> Result<(), GeneratedArtifactStoreError> {
    if record.artifact.store_binding.trim().is_empty()
        || record.artifact.object_version.trim().is_empty()
        || record.artifact.size_bytes == 0
        || record.artifact.media_type.trim().is_empty()
        || !valid_object_key(&record.object_key)
        || record.content_sha256.len() != 64
        || !record
            .content_sha256
            .bytes()
            .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
    {
        return Err(GeneratedArtifactStoreError::InvalidMetadata);
    }
    Ok(())
}

fn validate_reference(
    record: &GeneratedArtifactRecord,
    reference: &ArtifactRef,
) -> Result<(), GeneratedArtifactStoreError> {
    if reference.store_binding != record.artifact.store_binding
        || reference.object_version != record.artifact.object_version
        || reference.size_bytes != record.artifact.size_bytes
        || reference.media_type != record.artifact.media_type
    {
        return Err(GeneratedArtifactStoreError::IdentityMismatch);
    }
    Ok(())
}

/// Agent-owned generated-object metadata repository.
#[derive(Clone, Debug)]
pub struct GeneratedArtifactStore {
    pool: PgPool,
}

impl GeneratedArtifactStore {
    /// Creates a repository using the Agent schema pool.
    #[must_use]
    pub const fn new(pool: PgPool) -> Self {
        Self { pool }
    }

    /// Persists the exact object resolution after a verified immutable upload.
    ///
    /// The object upload and this row are separate resources.  A failed insert is returned to the
    /// caller so the generated result cannot be published with an unresolvable identity.
    #[allow(
        clippy::too_many_arguments,
        reason = "matches the generated artifact persistence contract"
    )]
    pub async fn register(
        &self,
        project_id: ProjectId,
        course_id: Option<CourseId>,
        package_id: ProblemPackageId,
        package_revision: Revision,
        kind: GeneratedArtifactKind,
        object_key: &str,
        reference: ArtifactRef,
        bytes: &[u8],
    ) -> Result<GeneratedArtifactRecord, GeneratedArtifactStoreError> {
        if !valid_object_key(object_key)
            || reference.size_bytes != u64::try_from(bytes.len()).unwrap_or(0)
            || reference.store_binding.trim().is_empty()
            || reference.object_version.trim().is_empty()
            || reference.media_type.trim().is_empty()
        {
            return Err(GeneratedArtifactStoreError::InvalidMetadata);
        }
        let record = GeneratedArtifactRecord {
            artifact: reference,
            project_id,
            course_id,
            package_id,
            package_revision,
            kind,
            object_key: object_key.to_owned(),
            content_sha256: Sha256Digest::of_bytes(bytes).to_string(),
        };
        validate_record(&record)?;
        let inserted = sqlx::query(
            "INSERT INTO agent.generated_artifacts \
             (artifact_id,project_id,course_id,package_id,package_revision,artifact_kind,object_key,object_version,size_bytes,content_sha256,store_binding,media_type) \
             VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) \
             ON CONFLICT (artifact_id) DO NOTHING",
        )
        .bind(record.artifact.artifact_id.as_uuid())
        .bind(record.project_id.as_uuid())
        .bind(record.course_id.map(CourseId::as_uuid))
        .bind(record.package_id.as_uuid())
        .bind(i64::try_from(record.package_revision.get()).map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?)
        .bind(kind_name(record.kind))
        .bind(&record.object_key)
        .bind(&record.artifact.object_version)
        .bind(i64::try_from(record.artifact.size_bytes).map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?)
        .bind(record.content_sha256.clone())
        .bind(&record.artifact.store_binding)
        .bind(&record.artifact.media_type)
        .execute(&self.pool)
        .await
        .map_err(|_| GeneratedArtifactStoreError::Persistence)?;
        if inserted.rows_affected() == 0 {
            let existing = self
                .get(
                    record.artifact.artifact_id,
                    &GeneratedArtifactQuery {
                        project_id,
                        course_id,
                        package_id,
                        package_revision,
                    },
                )
                .await?;
            if existing != record {
                return Err(GeneratedArtifactStoreError::IdentityMismatch);
            }
        }
        Ok(record)
    }

    /// Reads one exact generated-object resolution.
    pub async fn get(
        &self,
        artifact_id: ArtifactId,
        query: &GeneratedArtifactQuery,
    ) -> Result<GeneratedArtifactRecord, GeneratedArtifactStoreError> {
        let row = sqlx::query(
            "SELECT project_id,course_id,package_id,package_revision,artifact_kind,object_key,object_version,size_bytes,content_sha256,store_binding,media_type \
             FROM agent.generated_artifacts WHERE artifact_id=$1 AND project_id=$2 \
               AND course_id IS NOT DISTINCT FROM $3 AND package_id=$4 AND package_revision=$5",
        )
        .bind(artifact_id.as_uuid())
        .bind(query.project_id.as_uuid())
        .bind(query.course_id.map(CourseId::as_uuid))
        .bind(query.package_id.as_uuid())
        .bind(i64::try_from(query.package_revision.get()).map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?)
        .fetch_optional(&self.pool)
        .await
        .map_err(|_| GeneratedArtifactStoreError::Persistence)?
        .ok_or(GeneratedArtifactStoreError::NotFound)?;
        let project_id = parse_id::<ProjectId>(&row, "project_id")?;
        let course_id = row
            .try_get::<Option<uuid::Uuid>, _>("course_id")
            .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?
            .map(|value| CourseId::from_str(&value.to_string()))
            .transpose()
            .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?;
        let package_id = parse_id::<ProblemPackageId>(&row, "package_id")?;
        let package_revision = Revision::new(
            u64::try_from(
                row.try_get::<i64, _>("package_revision")
                    .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?,
            )
            .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?,
        )
        .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?;
        let kind_value = row
            .try_get::<String, _>("artifact_kind")
            .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?;
        let kind = parse_kind(&kind_value)?;
        let object_key = row
            .try_get::<String, _>("object_key")
            .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?;
        let object_version = row
            .try_get::<String, _>("object_version")
            .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?;
        let size_bytes = u64::try_from(
            row.try_get::<i64, _>("size_bytes")
                .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?,
        )
        .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?;
        let content_sha256 = row
            .try_get::<String, _>("content_sha256")
            .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?;
        let store_binding = row
            .try_get::<String, _>("store_binding")
            .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?;
        let media_type = row
            .try_get::<String, _>("media_type")
            .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?;
        let record = GeneratedArtifactRecord {
            artifact: ArtifactRef {
                artifact_id,
                store_binding,
                object_version,
                size_bytes,
                media_type,
            },
            project_id,
            course_id,
            package_id,
            package_revision,
            kind,
            object_key,
            content_sha256,
        };
        validate_record(&record)?;
        Ok(record)
    }

    /// Reads and verifies generated bytes through the Agent-owned resolution.
    #[allow(
        clippy::too_many_arguments,
        reason = "matches the generated artifact resolution contract"
    )]
    pub async fn read_verified(
        &self,
        objects: &S3ImmutableObjectStore,
        artifact_id: ArtifactId,
        project_id: ProjectId,
        course_id: Option<CourseId>,
        package_id: ProblemPackageId,
        package_revision: Revision,
        expected_kind: GeneratedArtifactKind,
    ) -> Result<(GeneratedArtifactRecord, Vec<u8>), GeneratedArtifactStoreError> {
        let query = GeneratedArtifactQuery {
            project_id,
            course_id,
            package_id,
            package_revision,
        };
        let record = self.get(artifact_id, &query).await?;
        if record.project_id != project_id
            || record.course_id != course_id
            || record.package_id != package_id
            || record.package_revision != package_revision
            || record.kind != expected_kind
        {
            return Err(GeneratedArtifactStoreError::IdentityMismatch);
        }
        let object = objects
            .read_verified(&record.object_key, &record.artifact)
            .await
            .map_err(GeneratedArtifactStoreError::Storage)?;
        validate_reference(&record, &object.reference)?;
        if Sha256Digest::of_bytes(&object.bytes).to_string() != record.content_sha256 {
            return Err(GeneratedArtifactStoreError::IdentityMismatch);
        }
        Ok((record, object.bytes))
    }

    /// Reads one generated object when the package revision is carried only by the Agent-owned
    /// artifact row.  Work execution plans intentionally expose the artifact reference but the
    /// retained Agent run contract does not duplicate the package revision.
    pub async fn read_verified_reference(
        &self,
        objects: &S3ImmutableObjectStore,
        reference: &ArtifactRef,
        project_id: ProjectId,
        course_id: Option<CourseId>,
        package_id: ProblemPackageId,
        expected_kind: GeneratedArtifactKind,
    ) -> Result<(GeneratedArtifactRecord, Vec<u8>), GeneratedArtifactStoreError> {
        let row = sqlx::query(
            "SELECT project_id,course_id,package_id,package_revision,artifact_kind,object_key,
                    object_version,size_bytes,content_sha256,store_binding,media_type
             FROM agent.generated_artifacts
             WHERE artifact_id=$1 AND project_id=$2
               AND course_id IS NOT DISTINCT FROM $3 AND package_id=$4",
        )
        .bind(reference.artifact_id.as_uuid())
        .bind(project_id.as_uuid())
        .bind(course_id.map(CourseId::as_uuid))
        .bind(package_id.as_uuid())
        .fetch_optional(&self.pool)
        .await
        .map_err(|_| GeneratedArtifactStoreError::Persistence)?
        .ok_or(GeneratedArtifactStoreError::NotFound)?;
        let package_revision = Revision::new(
            u64::try_from(
                row.try_get::<i64, _>("package_revision")
                    .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?,
            )
            .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?,
        )
        .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?;
        let record = self
            .get(
                reference.artifact_id,
                &GeneratedArtifactQuery {
                    project_id,
                    course_id,
                    package_id,
                    package_revision,
                },
            )
            .await?;
        if record.kind != expected_kind || record.artifact != *reference {
            return Err(GeneratedArtifactStoreError::IdentityMismatch);
        }
        let object = objects
            .read_verified(&record.object_key, &record.artifact)
            .await
            .map_err(GeneratedArtifactStoreError::Storage)?;
        validate_reference(&record, &object.reference)?;
        if Sha256Digest::of_bytes(&object.bytes).to_string() != record.content_sha256 {
            return Err(GeneratedArtifactStoreError::IdentityMismatch);
        }
        Ok((record, object.bytes))
    }
}

fn parse_id<T>(row: &sqlx::postgres::PgRow, column: &str) -> Result<T, GeneratedArtifactStoreError>
where
    T: FromStr,
{
    row.try_get::<uuid::Uuid, _>(column)
        .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)?
        .to_string()
        .parse()
        .map_err(|_| GeneratedArtifactStoreError::InvalidMetadata)
}

fn valid_object_key(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= MAX_OBJECT_KEY_BYTES
        && !value.contains("..")
        && !value.bytes().any(|byte| byte.is_ascii_control())
}

/// Stable Agent-owned generated-artifact failures.
#[derive(Debug, Error)]
pub enum GeneratedArtifactStoreError {
    /// The metadata row or supplied identity is malformed.
    #[error("generated artifact metadata is invalid")]
    InvalidMetadata,
    /// No row exists for the requested identity.
    #[error("generated artifact was not found")]
    NotFound,
    /// The object identity differs from the metadata row.
    #[error("generated artifact identity differs")]
    IdentityMismatch,
    /// Persistence failed.
    #[error("generated artifact metadata persistence failed")]
    Persistence,
    /// Object storage failed or returned a mismatched object.
    #[error("generated artifact object storage failed")]
    Storage(#[source] ObjectStoreError),
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use super::{GeneratedArtifactKind, GeneratedArtifactRecord, validate_record};
    use contracts::{ArtifactId, ArtifactRef, ProblemPackageId, ProjectId, Revision};

    fn record() -> GeneratedArtifactRecord {
        GeneratedArtifactRecord {
            artifact: ArtifactRef {
                artifact_id: ArtifactId::new(),
                store_binding: "agent-test-store".to_owned(),
                object_version: "version-1".to_owned(),
                size_bytes: 3,
                media_type: "text/x-shellscript".to_owned(),
            },
            project_id: ProjectId::new(),
            course_id: None,
            package_id: ProblemPackageId::new(),
            package_revision: Revision::new(1).expect("revision"),
            kind: GeneratedArtifactKind::WorkScript,
            object_key: "generated-work-configuration-scripts/project/script.sh".to_owned(),
            content_sha256: "4e07408562bedb8b60ce05c1decfe3ad16b72230967de01f640b7e4729b3f8e6"
                .to_owned(),
        }
    }

    #[test]
    fn metadata_requires_lowercase_digest_and_safe_key() {
        let mut valid = record();
        assert!(validate_record(&valid).is_ok());
        valid.content_sha256.replace_range(..1, "A");
        assert!(validate_record(&valid).is_err());
        let mut invalid_key = record();
        invalid_key.object_key = "generated/../script.sh".to_owned();
        assert!(validate_record(&invalid_key).is_err());
    }
}
