BatchMode yes
CanonicalizeHostname no
CheckHostIP yes
ConnectTimeout 10
ConnectionAttempts 1
ForwardAgent no
HashKnownHosts yes
IdentitiesOnly yes
IdentityFile /etc/labweaver/target_key
PasswordAuthentication no
KbdInteractiveAuthentication no
RequestTTY force
StrictHostKeyChecking yes
UserKnownHostsFile /etc/labweaver/known_hosts
