---
sprint2_buildkit_enabled: false
sprint2_buildkit_kubeconfig: /etc/kubernetes/admin.conf
sprint2_buildkit_namespace: labweaver-build
sprint2_buildkit_bundle: ""
sprint2_buildkit_manifest: "{{ playbook_dir }}/../../config/sprint2-buildkit-bundle-manifest.json"
sprint2_buildkit_storage_class: local-path
sprint2_buildkit_storage: 40Gi
sprint2_buildkit_registry_cidr: ""
sprint2_buildkit_dns_nameserver: ""
sprint2_buildkit_coredns_namespace: kube-system
sprint2_buildkit_coredns_configmap: coredns
sprint2_buildkit_harbor_hostname: harbor.lab.lan
sprint2_buildkit_harbor_tls_secret: harbor-nginx
sprint2_buildkit_operator_client_path: /home/rocky/.config/labweaver/buildkit
sprint2_buildkit_rollout_retries: 60
sprint2_buildkit_rollout_delay: 5
sprint2_buildkit_controller_enabled: false
sprint2_buildkit_controller_host: "{{ groups['routers'] | first }}"
sprint2_buildkit_controller_kubeconfig_source: ""
sprint2_buildkit_controller_kubeconfig: /home/rocky/.config/labweaver/package/kubeconfig
sprint2_buildkit_controller_api_server: ""
sprint2_buildkit_controller_api_address: ""
sprint2_buildkit_controller_client_path: /home/rocky/.config/labweaver/package/buildkit
sprint2_buildkit_controller_port: 1234
ansible_remote_tmp: /tmp/.ansible-labweaver
