apiVersion: v1
kind: ServiceAccount
metadata:
  name: labweaver-platform
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labweaver.labels" . | nindent 4 }}
automountServiceAccountToken: false
